project:
  type: book
  output-dir: _book

book:
  title: "Methods Brown Bag"
 # author:
 # - "Editors (2025-26)"
 # - "Sara Mohammadi(PhD $1^{st}$ Year)"
 # - "Parushya (PhD $4^{th}$ Year)"
  repo-url: https://github.com/govtmethods/methodsbrownbag
  repo-actions: [source, issue]
  chapters:
    - index.qmd
    - chapters/01-intro.qmd
    - chapters/02-github.qmd
    - chapters/02-Under-Regression.qmd

format:
  html:
    theme:
      light: journal # styles-light.scss]
      dark: cyborg # styles-dark.scss]
    toc: true
    toc-depth: 3
    code-fold: true
    code-overflow: wrap
    number-sections: false
    highlight-style: kate
    fig-path: "figures/html/"
    fig-format: png
    include-in-header:
      text: |
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Libre+Caslon+Text:wght@400;600&display=swap" rel="stylesheet">

  pdf:
    documentclass: report
    output-file: Methods-Brown-Bag.pdf
    toc: true
    code-fold: true
    code-overflow: wrap
    number-sections: false
    highlight-style: kate
    fig-path: "figures/pdf/"
    fig-format: pdf
    fontsize: 10pt
    linestretch: 1.15
    geometry: margin=1.1in

execute:
  freeze: false

keep-md: true
lightbox: true