<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.550">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Rong Qin &amp; Minha Kim">

<title>Methods Brown Bag Session: Network Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Brownbag_Network_files/libs/clipboard/clipboard.min.js"></script>
<script src="Brownbag_Network_files/libs/quarto-html/quarto.js"></script>
<script src="Brownbag_Network_files/libs/quarto-html/popper.min.js"></script>
<script src="Brownbag_Network_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Brownbag_Network_files/libs/quarto-html/anchor.min.js"></script>
<link href="Brownbag_Network_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Brownbag_Network_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Brownbag_Network_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Brownbag_Network_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Brownbag_Network_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#why-network-analysis" id="toc-why-network-analysis" class="nav-link active" data-scroll-target="#why-network-analysis">Why Network Analysis</a>
  <ul class="collapse">
  <li><a href="#example-1" id="toc-example-1" class="nav-link" data-scroll-target="#example-1">Example 1</a></li>
  <li><a href="#example-2" id="toc-example-2" class="nav-link" data-scroll-target="#example-2">Example 2</a></li>
  </ul></li>
  <li><a href="#network-introduction" id="toc-network-introduction" class="nav-link" data-scroll-target="#network-introduction">Network Introduction</a>
  <ul class="collapse">
  <li><a href="#basic-concepts-of-networks" id="toc-basic-concepts-of-networks" class="nav-link" data-scroll-target="#basic-concepts-of-networks">Basic Concepts of Networks</a></li>
  <li><a href="#view-of-networks" id="toc-view-of-networks" class="nav-link" data-scroll-target="#view-of-networks">View of Networks</a></li>
  <li><a href="#working-with-network-data" id="toc-working-with-network-data" class="nav-link" data-scroll-target="#working-with-network-data">Working With Network Data</a></li>
  </ul></li>
  <li><a href="#network-evaluations-descriptive-statistics" id="toc-network-evaluations-descriptive-statistics" class="nav-link" data-scroll-target="#network-evaluations-descriptive-statistics">Network Evaluations: Descriptive Statistics</a>
  <ul class="collapse">
  <li><a href="#path-diameter" id="toc-path-diameter" class="nav-link" data-scroll-target="#path-diameter">Path &amp; Diameter</a></li>
  <li><a href="#clustering-transitivity" id="toc-clustering-transitivity" class="nav-link" data-scroll-target="#clustering-transitivity">Clustering &amp; Transitivity</a></li>
  <li><a href="#homophily-assortativity" id="toc-homophily-assortativity" class="nav-link" data-scroll-target="#homophily-assortativity">Homophily &amp; Assortativity</a></li>
  </ul></li>
  <li><a href="#centralities" id="toc-centralities" class="nav-link" data-scroll-target="#centralities">Centralities</a>
  <ul class="collapse">
  <li><a href="#what-is-centrality" id="toc-what-is-centrality" class="nav-link" data-scroll-target="#what-is-centrality">What is centrality?</a></li>
  <li><a href="#network-centrality-measures" id="toc-network-centrality-measures" class="nav-link" data-scroll-target="#network-centrality-measures">Network centrality measures</a></li>
  </ul></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  <li><a href="#network-inference" id="toc-network-inference" class="nav-link" data-scroll-target="#network-inference">Network Inference</a>
  <ul class="collapse">
  <li><a href="#why-inference-in-network-analysis-is-special" id="toc-why-inference-in-network-analysis-is-special" class="nav-link" data-scroll-target="#why-inference-in-network-analysis-is-special">Why Inference in Network Analysis is Special</a></li>
  <li><a href="#hypothesis-testing-in-network-analysis" id="toc-hypothesis-testing-in-network-analysis" class="nav-link" data-scroll-target="#hypothesis-testing-in-network-analysis">Hypothesis Testing in Network Analysis?</a></li>
  <li><a href="#permutation-tests" id="toc-permutation-tests" class="nav-link" data-scroll-target="#permutation-tests">Permutation Tests</a></li>
  <li><a href="#ergms-exponential-random-graph-models" id="toc-ergms-exponential-random-graph-models" class="nav-link" data-scroll-target="#ergms-exponential-random-graph-models">ERGMs (Exponential Random Graph Models)</a></li>
  <li><a href="#further-readings" id="toc-further-readings" class="nav-link" data-scroll-target="#further-readings">Further Readings</a></li>
  <li><a href="#special-thanks" id="toc-special-thanks" class="nav-link" data-scroll-target="#special-thanks">Special Thanks</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Methods Brown Bag Session: Network Analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Rong Qin &amp; Minha Kim </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="why-network-analysis" class="level2">
<h2 class="anchored" data-anchor-id="why-network-analysis">Why Network Analysis</h2>
<p>“Actors do not behave or decide as atoms outside a social context… Their attempts at purposive action are instead embedded in concrete, ongoing systems of social relations.” (Granovetter 1985, 487)</p>
<ul>
<li>Granovetter: Economic action is <strong>embedded in ongoing social ties</strong>—neither atomized (undersocialized) nor fully dictated by roles (oversocialized). <strong>Networks provide information, trust, and sanctions</strong>, reducing opportunism and transaction costs.</li>
<li>Human action is situated within institutionalized relational contexts that structure thought, emotion, and conduct. These actions feed back into the very contexts that enable them, thereby influencing others and reshaping the social order.</li>
<li><strong>Embedded political action.</strong> Political behavior and institutions are <strong>situated in relational contexts</strong> (parties, coalitions, movements, alliances, supply chains). Actors pursue goals <strong>through</strong> these ties and, in doing so, <strong>reshape</strong> the networks that structure future action.</li>
<li>Many outcomes are <strong>networked</strong>: information spread, innovation diffusion, cooperation/conflict. And Networks can capture <strong>dependencies</strong> (reciprocity, homophily, triadic closure) that individual-level models miss.</li>
</ul>
<section id="example-1" class="level3">
<h3 class="anchored" data-anchor-id="example-1">Example 1</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Images/Image_title1.png" class="img-fluid figure-img" width="500"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Images/Imgae_figure1.png" class="img-fluid figure-img" width="500"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="example-2" class="level3">
<h3 class="anchored" data-anchor-id="example-2">Example 2</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Images/Image_Kinneabstract.png" class="img-fluid figure-img" width="500"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Images/Image_Kinnefigure.png" class="img-fluid figure-img" width="500"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Mass behavior &amp; opinion: discussion networks → turnout, persuasion, polarization.</li>
<li>Parties &amp; elites: endorsements, donor ties, activists/interest groups → factions &amp; leadership.</li>
<li>Movements &amp; mobilization: protest cascades, organizational networks, brokerage under repression.</li>
<li>Security networks: alliances, basing, intelligence sharing → deterrence, burden sharing.</li>
<li>IPE &amp; global production: trade/finance/supply chains → leverage, vulnerability, sanctions.</li>
</ul>
<details>
<summary>
<strong>Further Readings (click to expand)</strong>
</summary>
<ul>
<li>Granovetter, Mark. “Economic Action and Social Structure: The Problem of Embeddedness.” <em>American Journal of Sociology</em> 91, no. 3 (1985): 481–510. http://www.jstor.org/stable/2780199.</li>
<li>Scott, John. <em>Social Network Analysis</em>. Fourth. 55 City Road, London: SAGE Publications Ltd, 2017. https://doi.org/10.4135/9781529716597.</li>
<li>Cranmer, Skyler J., and Bruce A. Desmarais. “Inferential Network Analysis with Exponential Random Graph Models.” Political Analysis 19, no. 1 (2011): 66–86. https://doi-org.proxy.library.georgetown.edu/10.1093/pan/mpq037.</li>
<li>Hafner-Burton, Emilie M., Miles Kahler, and Alexander H. Montgomery. “Network Analysis for International Relations.” <em>International Organization</em> 63, no. 3 (2009): 559–92. https://doi-org.proxy.library.georgetown.edu/10.1017/S0020818309090195.</li>
<li>Jackson, Patrick Thaddeus, and Daniel H. Nexon. 2019. “Reclaiming the Social: Relationalism in Anglophone International Studies.” <em>Cambridge Review of International Affairs</em> 32 (5): 582–600. https://doi.org/10.1080/09557571.2019.1567460.</li>
<li>Nexon, Daniel H. “Network Theory and Grand Strategy.” In <em>The Oxford Handbook of Grand Strategy</em>, edited by Thierry Balzacq and Ronald R. Krebs. Oxford Academic, 2021. https://doi-org.proxy.library.georgetown.edu/10.1093/oxfordhb/9780198840299.013.7. Accessed 2 Oct.&nbsp;2025.</li>
<li>Farrell, Henry, and Abraham L. Newman. “Weaponized Interdependence: How Global Economic Networks Shape State Coercion.” <em>International Security</em> 44, no. 1 (2019): 42–79. https://doi.org/10.1162/isec_a_00351.</li>
<li>Noel, Hans. 2012. “Towards a Networks Theory of Political Parties: A Social Networks Analysis of Internal Party Cleavages in Presidential Nominations, 1972–2008.” Paper presented at American Political Parties: Past, Present, and Future, University of Virginia, Charlottesville, October 8–9. https://faculty.georgetown.edu/hcn4/Downloads/Noel_SNA_UVa.pdf</li>
<li>Bailey, Michael, Rachel Cao, Theresa Kuchler, Johannes Stroebel, and Arlene Wong. 2018. “Social Connectedness: Measurement, Determinants, and Effects.” <em>Journal of Economic Perspectives</em> 32 (3): 259–80. https://doi.org/10.1257/jep.32.3.259.</li>
<li>Winecoff, W. K. 2020. “The Persistent Myth of Lost Hegemony, Revisited: Structural Power as a Complex Network Phenomenon.” <em>European Journal of International Relations</em> 26 (1_suppl): 209–252. https://doi-org.proxy.library.georgetown.edu/10.1177/1354066120952876.</li>
<li>Kinne, Brandon J., and Stephanie N. Kang. “Free Riding, Network Effects, and Burden Sharing in Defense Cooperation Networks.” <em>International Organization</em> 77, no. 2 (2023): 405–39. https://doi-org.proxy.library.georgetown.edu/10.1017/S0020818322000315.</li>
</ul>
</details>
</section>
</section>
<section id="network-introduction" class="level2">
<h2 class="anchored" data-anchor-id="network-introduction">Network Introduction</h2>
<section id="basic-concepts-of-networks" class="level3 mb-3">
<h3 class="mb-3 anchored" data-anchor-id="basic-concepts-of-networks">Basic Concepts of Networks</h3>
<p><strong>Node</strong>: The things that are connected in a network (also called vertices).</p>
<p><strong>Edges, Ties, or Links</strong>: The connections between nodes.</p>
<p><strong>Degree</strong>: The number of edges a node has.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>A node with high degree (many connections) is called a <strong>hub</strong>.</p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Images/Image1.png" class="img-fluid figure-img" width="350"></p>
</figure>
</div>
</div>
</div>
<p><strong>Weights</strong>: Edges may have different weights, indicating the strength of the connection.</p>
<p><strong>Direction</strong>: Edges can be directed or undirected.</p>
<ul>
<li>In-degree: Number of connections received.</li>
<li>Out-degree: Number of connections gave.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Images/Image2.png" class="img-fluid figure-img" width="450"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="view-of-networks" class="level3 mb-3">
<h3 class="mb-3 anchored" data-anchor-id="view-of-networks">View of Networks</h3>
<p><strong>Egocentric Networks</strong>: An ego-net is one person’s local perspective of a network.</p>
<p><strong>Whole Network</strong>: Whole network means that we know ALL nodes and edges of our network</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The data on the whole networks is usually challenging to come by in many fields (maybe IR is an exception?).</p>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Images/Image5.png" class="img-fluid figure-img" width="600"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="working-with-network-data" class="level3 mb-3">
<h3 class="mb-3 anchored" data-anchor-id="working-with-network-data">Working With Network Data</h3>
<ul>
<li><strong>Edge List</strong></li>
</ul>
<p>Edge list is a concise way to summarize network structures.</p>
<ul>
<li><strong>Adjacency Matrix</strong></li>
</ul>
<p>Adjacency matrix includes more information than an edge list (e.g., it includes isolates) but also takes up more space.</p>
<div class="columns">
<div class="column" style="width:65%;">
<p><img src="Images/Image3.png" class="img-fluid"></p>
</div><div class="column" style="width:35%;">
<p><img src="Images/Image4.png" class="img-fluid"></p>
</div>
</div>
</section>
</section>
<section id="network-evaluations-descriptive-statistics" class="level2">
<h2 class="anchored" data-anchor-id="network-evaluations-descriptive-statistics">Network Evaluations: Descriptive Statistics</h2>
<section id="path-diameter" class="level3">
<h3 class="anchored" data-anchor-id="path-diameter">Path &amp; Diameter</h3>
<ul>
<li>A <strong>path</strong> is any traversal of edges from any node <span class="math inline">\(n_i\)</span> to any other node <span class="math inline">\(n_j\)</span></li>
<li>The shortest path between nodes <span class="math inline">\(n_i\)</span> and <span class="math inline">\(n_j\)</span> is the path with the fewest traversals</li>
<li>The <strong>diameter</strong> of a network is defined as the length of the longest shortest path in the network</li>
</ul>
</section>
<section id="clustering-transitivity" class="level3">
<h3 class="anchored" data-anchor-id="clustering-transitivity">Clustering &amp; Transitivity</h3>
<ul>
<li><strong>Clustering</strong> is a measure of how <em>locally</em> interconnected a network is</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Images/Image6.png" class="img-fluid figure-img" width="600"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><strong>Network level clustering (transitivity)</strong> examines the proportion of closed traids among all the traids in a network.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Images/Image7.png" class="img-fluid figure-img" width="600"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="homophily-assortativity" class="level3">
<h3 class="anchored" data-anchor-id="homophily-assortativity">Homophily &amp; Assortativity</h3>
<ul>
<li><strong>Homophily</strong> means that nodes tend to be connected with similar ones.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Images/Image8.png" class="img-fluid figure-img" width="600"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><strong>Assortativity</strong> measures the likelihood nodes are connected with those of similar degrees.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Assortativity</strong> is basically an operationalization of homophily, degree homophily.</p>
</div>
</div>
</section>
</section>
<section id="centralities" class="level2">
<h2 class="anchored" data-anchor-id="centralities">Centralities</h2>
<section id="what-is-centrality" class="level3">
<h3 class="anchored" data-anchor-id="what-is-centrality">What is centrality?</h3>
<ul>
<li><strong>Centrality</strong> is a property of a node in a graph.</li>
<li>People often talk about centrality as a measure of prominence or importance</li>
<li>There are different conceptions of what it means to be “central”
<ul>
<li><strong>Power</strong>: Control the flow of resources / information</li>
<li><strong>Independence</strong>: Able to be free of control</li>
<li><strong>Influence</strong>: Able to influence other people</li>
</ul></li>
</ul>
</section>
<section id="network-centrality-measures" class="level3">
<h3 class="anchored" data-anchor-id="network-centrality-measures">Network centrality measures</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Images/Image9.png" class="img-fluid figure-img" width="600"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p><strong>Degree Centrality</strong>: The degree of a node is the number of other nodes that single node is connected to. Important nodes tend to have more connections to other nodes. Highly connected nodes are interpreted to have high degree centrality.</p></li>
<li><p><strong>Eigenvector Centrality</strong>: The extent to which adjacent nodes are connected themselves also indicate importance (e.g., Important nodes increase the importance of other nodes). A measure that takes into account the centrality of a node’s neighbors (the nodes it is connected to)</p></li>
<li><p><strong>Closeness centrality</strong>: Closeness centrality measures how many steps are required to access every other node from a given node. In other words, important nodes have easy access to other nodes given multiple connections.</p></li>
<li><p><strong>Betweenness Centrality</strong>: This ranks the nodes based on the flow of connections through the network. Importance is demonstrated through high frequency of connection with multiple other nodes. Nodes with high levels of betweenness tend to serve as a bridge for multiple sets of other important nodes.</p></li>
</ul>
</section>
</section>
<section id="exercises" class="level2">
<h2 class="anchored" data-anchor-id="exercises">Exercises</h2>
<p>Call out all the packages that would be needed</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(igraph)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(statnet)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(intergraph)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ergm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Call out the dataset and explore it a bit.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(florentine)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(flomarriage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "network"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(flomarriage) <span class="do">## see the edgelist matrix stored in this network object</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Network attributes:
  vertices = 16
  directed = FALSE
  hyper = FALSE
  loops = FALSE
  multiple = FALSE
  bipartite = FALSE
 total edges = 20 
   missing edges = 0 
   non-missing edges = 20 
 density = 0.1666667 

Vertex attributes:

 priorates:
   numeric valued attribute
   attribute summary:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   0.00    0.00   21.50   25.94   44.75   74.00 

 totalties:
   numeric valued attribute
   attribute summary:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   1.00    4.75    9.00   13.88   15.00   54.00 
  vertex.names:
   character valued attribute
   16 valid vertex names

 wealth:
   numeric valued attribute
   attribute summary:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   3.00   17.50   39.00   42.56   48.25  146.00 

No edge attributes

Network edgelist matrix:
      [,1] [,2]
 [1,]    1    9
 [2,]    2    6
 [3,]    2    7
 [4,]    2    9
 [5,]    3    5
 [6,]    3    9
 [7,]    4    7
 [8,]    4   11
 [9,]    4   15
[10,]    5   11
[11,]    5   15
[12,]    7    8
[13,]    7   16
[14,]    9   13
[15,]    9   14
[16,]    9   16
[17,]   10   14
[18,]   11   15
[19,]   13   15
[20,]   13   16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">as.matrix.network.adjacency</span>(flomarriage)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>g_flomarriage  <span class="ot">&lt;-</span> <span class="fu">graph_from_adjacency_matrix</span>(A, <span class="at">mode =</span> <span class="st">"undirected"</span>, <span class="at">diag =</span> <span class="cn">FALSE</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Bring over labels and vertex attributes</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="fu">V</span>(g_flomarriage)<span class="sc">$</span>name     <span class="ot">&lt;-</span> <span class="fu">network.vertex.names</span>(flomarriage)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="fu">V</span>(g_flomarriage)<span class="sc">$</span>wealth   <span class="ot">&lt;-</span> flomarriage <span class="sc">%v%</span> <span class="st">"wealth"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s check out how that adjacency matrix looks like</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>A</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Acciaiuoli Albizzi Barbadori Bischeri Castellani Ginori Guadagni
Acciaiuoli            0       0         0        0          0      0        0
Albizzi               0       0         0        0          0      1        1
Barbadori             0       0         0        0          1      0        0
Bischeri              0       0         0        0          0      0        1
Castellani            0       0         1        0          0      0        0
Ginori                0       1         0        0          0      0        0
Guadagni              0       1         0        1          0      0        0
Lamberteschi          0       0         0        0          0      0        1
Medici                1       1         1        0          0      0        0
Pazzi                 0       0         0        0          0      0        0
Peruzzi               0       0         0        1          1      0        0
Pucci                 0       0         0        0          0      0        0
Ridolfi               0       0         0        0          0      0        0
Salviati              0       0         0        0          0      0        0
Strozzi               0       0         0        1          1      0        0
Tornabuoni            0       0         0        0          0      0        1
             Lamberteschi Medici Pazzi Peruzzi Pucci Ridolfi Salviati Strozzi
Acciaiuoli              0      1     0       0     0       0        0       0
Albizzi                 0      1     0       0     0       0        0       0
Barbadori               0      1     0       0     0       0        0       0
Bischeri                0      0     0       1     0       0        0       1
Castellani              0      0     0       1     0       0        0       1
Ginori                  0      0     0       0     0       0        0       0
Guadagni                1      0     0       0     0       0        0       0
Lamberteschi            0      0     0       0     0       0        0       0
Medici                  0      0     0       0     0       1        1       0
Pazzi                   0      0     0       0     0       0        1       0
Peruzzi                 0      0     0       0     0       0        0       1
Pucci                   0      0     0       0     0       0        0       0
Ridolfi                 0      1     0       0     0       0        0       1
Salviati                0      1     1       0     0       0        0       0
Strozzi                 0      0     0       1     0       1        0       0
Tornabuoni              0      1     0       0     0       1        0       0
             Tornabuoni
Acciaiuoli            0
Albizzi               0
Barbadori             0
Bischeri              0
Castellani            0
Ginori                0
Guadagni              1
Lamberteschi          0
Medici                1
Pazzi                 0
Peruzzi               0
Pucci                 0
Ridolfi               1
Salviati              0
Strozzi               0
Tornabuoni            0</code></pre>
</div>
</div>
<p>Let’s look at the centralities of the families in this network.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>deg  <span class="ot">&lt;-</span> igraph<span class="sc">::</span><span class="fu">degree</span>(g_flomarriage)  </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>bet  <span class="ot">&lt;-</span> igraph<span class="sc">::</span><span class="fu">betweenness</span>(g_flomarriage, <span class="at">directed =</span> <span class="cn">FALSE</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>clo  <span class="ot">&lt;-</span> igraph<span class="sc">::</span><span class="fu">closeness</span>(g_flomarriage)  </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>eig  <span class="ot">&lt;-</span> igraph<span class="sc">::</span><span class="fu">eigen_centrality</span>(g_flomarriage, <span class="at">directed =</span> <span class="cn">FALSE</span>)<span class="sc">$</span>vector</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>centralities <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">family      =</span> <span class="fu">V</span>(g_flomarriage)<span class="sc">$</span>name,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">degree      =</span> deg,</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">betweenness =</span> bet,</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">closeness   =</span> clo,</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">eigenvector =</span> eig</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>vsize <span class="ot">&lt;-</span> <span class="dv">10</span> <span class="sc">+</span> <span class="dv">30</span> <span class="sc">*</span> (deg <span class="sc">-</span> <span class="fu">min</span>(deg)) <span class="sc">/</span> (<span class="fu">max</span>(deg) <span class="sc">-</span> <span class="fu">min</span>(deg) <span class="sc">+</span> <span class="fl">1e-9</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  g_flomarriage, <span class="at">layout =</span> igraph<span class="sc">::</span><span class="fu">layout_with_fr</span>(g_flomarriage),</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">vertex.size =</span> vsize<span class="sc">+</span><span class="dv">2</span>,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">vertex.label =</span> <span class="fu">V</span>(g_flomarriage)<span class="sc">$</span>name,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">vertex.label.cex =</span> <span class="fl">0.9</span>,</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">vertex.frame.color =</span> <span class="cn">NA</span>,</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">edge.width =</span> <span class="fl">1.2</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Brownbag_Network_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>How about different layout formats? Try <code>layout_with_kk</code>, <code>layout_with_drl</code>, or <code>layout_in_circle</code>.</p>
</div>
</div>
</section>
<section id="network-inference" class="level2">
<h2 class="anchored" data-anchor-id="network-inference">Network Inference</h2>
<section id="why-inference-in-network-analysis-is-special" class="level3">
<h3 class="anchored" data-anchor-id="why-inference-in-network-analysis-is-special">Why Inference in Network Analysis is Special</h3>
<ul>
<li>Inference in genral statistics relies on assumptions of independence (e.g., each observation is i.i.d.).</li>
<li>In networks, <strong>edges (ties)</strong> are <strong>not independent</strong>
<ul>
<li>Think about the mechanisms like triadic closure or preferential attachment</li>
</ul></li>
<li>Standard regression approaches can break down if you ignore this dependence.</li>
<li>Inference in network analysis means <strong>testing whether observed patterns (like reciprocity, homophily, or clustering) are due to chance or to systematic processes</strong>.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Yes, you generally cannot use network measures as outcome variables in most forms of regression (because this violates the assumption of independence). However, as predictors, network measures can be used (with caution!). For example, various forms of node centrality are commonly used as IVs. But note that multicollinearity is a common issue (e.g., degree, betweenness, eigenvector centrality often overlap).</p>
</div>
</div>
</section>
<section id="hypothesis-testing-in-network-analysis" class="level3">
<h3 class="anchored" data-anchor-id="hypothesis-testing-in-network-analysis">Hypothesis Testing in Network Analysis?</h3>
<p>Let’s say we observed network transitivity (clustering) of 0.08. But by itself, the number is hard to interpret. Is that large or small? How surprising is the value we observed?</p>
<ul>
<li><strong>H0</strong>: The observed clustering is due to random chance</li>
<li><strong>H1:</strong> The observed clustering is NOT due to random chance (In descriptive studies, this is typically the strongest statement we can make. But we might also want to answer <em>why</em>)</li>
</ul>
<!-- -->
<p>How can we tell if our network’s pattern is more than chance when we only observe one network? Ideally, we need to compare our observed network to ALL potential networks. But how do we generate these “alternate universe” networks? We use <strong>simulation</strong> to create many comparable networks, then compare the observed statistic to the simulated distribution (get a p-value / quantile).</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Images/Image_P.png" class="img-fluid figure-img" width="500"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Images/Image_landscape.png" class="img-fluid figure-img" width="800"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="permutation-tests" class="level3">
<h3 class="anchored" data-anchor-id="permutation-tests">Permutation Tests</h3>
<ul>
<li><p>Estimate the probability of observing a specific network-level statistic (e.g., clustering, reciprocity, centralization).</p></li>
<li><p>Work by <strong>shuffling</strong> the data according to defined rules (e.g., randomly re-wire edges).</p></li>
<li><p><strong>Control for network structure:</strong></p>
<ul>
<li><p>When asking “Is clustering higher than random?”, we don’t want bias from density or degree distribution.</p></li>
<li><p>During permutation, preserve certain properties of the observed network:</p>
<ul>
<li><strong>Preserve density</strong>: keep the same number of edges, but rewire them randomly.</li>
<li><strong>Preserve degree distribution</strong>: each node keeps the same number of ties, but partners are randomized.</li>
</ul></li>
</ul></li>
<li><p>This creates a <strong>universe of possible networks</strong> (a null model = permutations of the observed network) that matches observed density/degree distribution.</p></li>
<li><p>Useful for testing whether a network statistic is <strong>significantly different from random</strong>, while accounting for node inter-dependence. It can also test whether the similarity between two networks is significantly different from random.</p></li>
<li><p>Good for descriptive inference.</p></li>
<li><p>But cannot test <em>why</em> a pattern occurs.</p></li>
</ul>
</section>
<section id="ergms-exponential-random-graph-models" class="level3">
<h3 class="anchored" data-anchor-id="ergms-exponential-random-graph-models">ERGMs (Exponential Random Graph Models)</h3>
<ul>
<li><p>“Of all possible networks we could have observed, what’s the probability of observing the one we did?”</p></li>
<li><p>ERGMs can answer questions such as…</p>
<ul>
<li>What is the probability of tie formation in the observed network?</li>
<li>What effect does <strong>homophily</strong> have on tie formation?</li>
<li>What effect does <strong>triadic closure</strong> have on tie formation?</li>
<li>What effect does a <strong>node characteristic</strong> (e.g., wealth, gender) have on tie formation?</li>
<li>What role does a <strong>specific node with a specific attribute</strong> play in tie formation?</li>
</ul></li>
<li><p>ERGM treats the entire network (adjacency matrix) as a <strong>single multivariate observation</strong> (no i.i.d. dyads).</p></li>
<li><p>Model the probability of the observed network as a function of specified features.</p>
<ul>
<li>Each feature (reciprocity, triangles, homophily, covariates) is added as a term.</li>
<li>ERGM estimates coefficients → show how strongly each feature influences tie formation.</li>
</ul></li>
<li><p>We want <span class="math inline">\(P(N)\)</span>, the probability of observing network <span class="math inline">\(N\)</span>. Let <span class="math inline">\(h(N)\)</span> be a vector of network statistics (captures interdependence among edges + covariates).</p></li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<p><img src="Images/Image_ERGM0.png" class="img-fluid"></p>
</div><div class="column" style="width:50%;">
<p><img src="Images/Image_ERGM1.png" class="img-fluid"></p>
</div>
</div>
<section id="ergms-exponential-random-graph-models-exercise" class="level4">
<h4 class="anchored" data-anchor-id="ergms-exponential-random-graph-models-exercise">ERGMs (Exponential Random Graph Models) Exercise</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Images/Image_ERGM3.png" class="img-fluid figure-img" width="500"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Images/Image_ERGM4.png" class="img-fluid figure-img" width="500"></p>
</figure>
</div>
</div>
</div>
<p>Let’s just see how it works! Let’s first see what we have in our data. We can see the items in our environment using:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ls</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "A"             "bet"           "centralities"  "clo"          
 [5] "deg"           "eig"           "flobusiness"   "flomarriage"  
 [9] "g_flomarriage" "vsize"        </code></pre>
</div>
</div>
<p><strong>flobusiness</strong> contains the network of business ties and <strong>flomarriage</strong> contains the network of marriage ties.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s start with a simple model which estimates the probability of seeing our network of marriage ties as a function of the number of edges in our network:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>ergm1 <span class="ot">&lt;-</span> <span class="fu">ergm</span>(flomarriage<span class="sc">~</span> edges)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Starting maximum pseudolikelihood estimation (MPLE):</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Obtaining the responsible dyads.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Evaluating the predictor and response matrix.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Maximizing the pseudolikelihood.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Finished MPLE.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Evaluating log-likelihood at the estimate. </code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ergm1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
ergm(formula = flomarriage ~ edges)

Maximum Likelihood Results:

      Estimate Std. Error MCMC % z value Pr(&gt;|z|)    
edges  -1.6094     0.2449      0  -6.571   &lt;1e-04 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

     Null Deviance: 166.4  on 120  degrees of freedom
 Residual Deviance: 108.1  on 119  degrees of freedom
 
AIC: 110.1  BIC: 112.9  (Smaller is better. MC Std. Err. = 0)</code></pre>
</div>
</div>
<p>This model specifies a single homogeneous probability for all ties, which is captured by the <strong>edges coefficient</strong> (θ<sub>E</sub>). To interpret this coefficient, we can return to the logit form of the ERGM.</p>
<p>The ERGM can be written in logistic form:</p>
<p><span class="math display">\[
  \operatorname{logit}(p_{ij}) = \theta_E \,\delta^{E}_{ij}(N)
  \]</span></p>
<ul>
<li><p>Where:</p>
<ul>
<li><span class="math inline">\(\theta_E\)</span> = coefficient for edges (here: <span class="math inline">\(-1.6094\)</span>).</li>
<li><span class="math inline">\(\delta^{E}_{ij}(N)\)</span> = change in the edge count when adding edge <span class="math inline">\(ij\)</span>.</li>
</ul></li>
<li><p>Adding an edge always increases the edge count by 1:</p>
<p><span class="math display">\[
\delta^{E}_{ij}(N) = 1
\]</span></p>
<p>So the formula simplifies to:</p>
<p><span class="math display">\[
\operatorname{logit}(p_{ij}) = \theta_E
\]</span></p></li>
<li><p>To get the probability, take the inverse logit:</p>
<p><span class="math display">\[
p_{ij} = \frac{e^{\theta_E}}{1 + e^{\theta_E}}
\]</span></p></li>
</ul>
<p>With θ<sub>E</sub> = –1.6094:</p>
<p><span class="math display">\[
p_{ij} = \frac{e^{-1.6094}}{1 + e^{-1.6094}} \approx 0.167
\]</span></p>
<p>We can use R to calculate:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fl">1.6094</span>) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fl">1.6094</span>))</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>p</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1666719</code></pre>
</div>
</div>
<p>The probability of an edge existing between i and j is 0.167. This is the baseline ERGM: it only accounts for network density (how many edges exist).</p>
<p>We can also do this with node-level covariate data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">list.vertex.attributes</span>(flomarriage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "na"           "priorates"    "totalties"    "vertex.names" "wealth"      </code></pre>
</div>
</div>
<p>Let’s see how the “wealth” affects the tie formation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get.vertex.attribute</span>(flomarriage, <span class="st">"wealth"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  10  36  55  44  20  32   8  42 103  48  49   3  27  10 146  48</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">get.vertex.attribute</span>(flomarriage, <span class="st">"wealth"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   3.00   17.50   39.00   42.56   48.25  146.00 </code></pre>
</div>
</div>
<p>Let’s do some “pre-checks” to sanity-check the covariate and inspect the model’s sufficient statistics before estimating the ERGM. We check range/skew/outliers or missingness. We should also see whether units are large/uneven, so that we can consider centering/scaling (or logging) for stability and interpretation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">get.vertex.attribute</span>(flomarriage, <span class="st">"wealth"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   3.00   17.50   39.00   42.56   48.25  146.00 </code></pre>
</div>
</div>
<p>These are the ERGM sufficient statistics 𝑔 ( 𝑦 ) for your formula.Do you get the terms you expect? Are they non-zero? (If a term returns 0 or NA, the model can’t identify it.)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(flomarriage<span class="sc">~</span> edges <span class="sc">+</span> <span class="fu">nodecov</span>(<span class="st">'wealth'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         edges nodecov.wealth 
            20           2168 </code></pre>
</div>
</div>
<p>Now we run an ERGM with two parameters: edges and family wealth:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>ergm2 <span class="ot">&lt;-</span> <span class="fu">ergm</span>(flomarriage<span class="sc">~</span> edges <span class="sc">+</span> <span class="fu">nodecov</span>(<span class="st">'wealth'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Starting maximum pseudolikelihood estimation (MPLE):</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Obtaining the responsible dyads.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Evaluating the predictor and response matrix.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Maximizing the pseudolikelihood.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Finished MPLE.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Evaluating log-likelihood at the estimate. </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ergm2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
ergm(formula = flomarriage ~ edges + nodecov("wealth"))

Maximum Likelihood Results:

                Estimate Std. Error MCMC % z value Pr(&gt;|z|)    
edges          -2.594929   0.536056      0  -4.841   &lt;1e-04 ***
nodecov.wealth  0.010546   0.004674      0   2.256   0.0241 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

     Null Deviance: 166.4  on 120  degrees of freedom
 Residual Deviance: 103.1  on 118  degrees of freedom
 
AIC: 107.1  BIC: 112.7  (Smaller is better. MC Std. Err. = 0)</code></pre>
</div>
</div>
<p>Baseline ties are unlikely (edges coefficient <span class="math inline">\(\approx -2.595\)</span>). Wealth has a small, positive, statistically significant effect(although barely at the 5% level) on tie formation (<span class="math inline">\(\beta_{\text{wealth}} \approx 0.0105\)</span>, <span class="math inline">\(p \approx 0.024\)</span>). Let’s plug in values to see the implied probabilities.</p>
<ul>
<li><p><strong>Model (logit form)</strong></p>
<p><span class="math display">\[
\operatorname{logit}(p_{ij}) \;=\; -2.594929 \;+\; 0.010546\,(\text{wealth}_i + \text{wealth}_j)
\]</span></p>
<p>where <span class="math inline">\(\operatorname{logit}^{-1}(x)=\dfrac{e^{x}}{1+e^{x}}\)</span> converts log-odds to probability.</p></li>
<li><p><strong>Example 1: each family has wealth = 1</strong></p>
<p><span class="math display">\[
\operatorname{logit}(p_{ij}) = -2.594929 + 0.010546(1+1) = -2.573837
\]</span></p>
<p><span class="math display">\[
p_{ij} \;=\; \operatorname{logit}^{-1}(-2.573837)
         \;=\; \frac{e^{-2.573837}}{1+e^{-2.573837}}
         \;\approx\; 0.071
\]</span></p></li>
<li><p><strong>Example 2: each family has wealth = 100</strong></p>
<p><span class="math display">\[
\operatorname{logit}(p_{ij}) = -2.594929 + 0.010546(100+100) = -0.485729
\]</span></p>
<p><span class="math display">\[
p_{ij} \;=\; \operatorname{logit}^{-1}(-0.485729)
         \;=\; \frac{e^{-0.485729}}{1+e^{-0.485729}}
         \;\approx\; 0.381
\]</span></p></li>
</ul>
<p>This model suggests that wealthier families are more likely to have ties, but the effect size per wealth unit is small. Each +1 to (wealth_i + wealth_j) multiplies the odds by exp(0.0105) ≈ 1.011 (~1.1% increase per unit).</p>
</section>
</section>
<section id="further-readings" class="level3">
<h3 class="anchored" data-anchor-id="further-readings">Further Readings</h3>
<ul>
<li><a href="https://cran.r-project.org/web/packages/ergmito/vignettes/ergm-equations.html">ERGM equation</a></li>
<li><a href="https://statnet.org/workshop-ergm/ergm_tutorial.html">ERGMs tutorial (statnet)</a></li>
</ul>
</section>
<section id="special-thanks" class="level3">
<h3 class="anchored" data-anchor-id="special-thanks">Special Thanks</h3>
<p>The authors of this document want to express special thanks to Professor Sarah Shugars from Rutgers University. This document has used the resources from Professor Shugars’ Network Analysis session at ICPSR (2023 and 2024).</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>